linters:
    LineLength:
        max: 120
        severity: error
    Indentation:
        character: space
        width: 4
        severity: error
exclude:
    # Defaults
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    # Project
    - 'bin/*'
    - 'db/schema.rb'

